/**
 * $File: JCS_RouteGuageSystem.cs $
 * $Date: 2017-05-01 $
 * $Revision: $
 * $Creator: Jen-Chieh Shen $
 * $Notice: See LICENSE.txt for modification and distribution information 
 *                   Copyright (c) 2017 by Shen, Jen-Chieh $
 */
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using JCSUnity;


namespace JCSUnity
{

    /// <summary>
    /// Minimap of all the racers.
    /// 
    /// SOURCE: https://www.youtube.com/watch?v=yqMIfTWoA8A
    /// </summary>
    public class JCS_RouteGuageSystem
        : MonoBehaviour
    {
        //----------------------
        // Public Variables

        //----------------------
        // Private Variables

        [System.Serializable]
        public struct PlayerRegisterForm
        {
            [Tooltip("Player's transform.")]
            public Transform playerTransform;

            [Tooltip("Sprite transfrom represent this player.")]
            public Transform spriteTransform;
        };


        [Header("** Check Variables (JCS_RouteGuageSystem) **")]

        [Tooltip("Distance between the starting line and goal.")]
        [SerializeField]
        private float mRealDistance = 0;

        [Tooltip("")]
        [SerializeField]
        private float mSpriteDistance = 0;

        [Tooltip("Ratio between real distance and sprite ditance.")]
        [SerializeField]
        private float mDistanceRatio = 0;


        [Header("** Initialize Variables (JCS_RouteGuageSystem) **")]

        [Tooltip("Starting line position.")]
        [SerializeField]
        private Transform mRealStartTransform = null;

        [Tooltip("Goal position")]
        [SerializeField]
        private Transform mRealGoalTransfrom = null;

        [Tooltip("Start transform for sprite.")]
        [SerializeField]
        private Transform mSpriteStartTransform = null;

        [Tooltip("Goal transform for sprite.")]
        [SerializeField]
        private Transform mSpriteGoalTransform = null;

        [Header("** Runtime Variables (JCS_RouteGuageSystem) **")]

        [Tooltip("")]
        [SerializeField]
        private PlayerRegisterForm[] mPlayersForm = null;

        //----------------------
        // Protected Variables

        //========================================
        //      setter / getter
        //------------------------------

        //========================================
        //      Unity's function
        //------------------------------
        private void Awake()
        {
            // get the position from two target transform.
            this.mRealDistance = Vector3.Distance(
                mRealGoalTransfrom.position, mRealStartTransform.position);

            this.mSpriteDistance = Vector3.Distance(
                mSpriteGoalTransform.position, mSpriteStartTransform.position);

            // get the ratio from real distance and sprite distance.
            mDistanceRatio = mSpriteDistance / mRealDistance;
        }

        private void Update()
        {
            DoRouteGuage();
        }

        //========================================
        //      Self-Define
        //------------------------------
        //----------------------
        // Public Functions

        //----------------------
        // Protected Functions

        //----------------------
        // Private Functions
        /// <summary>
        /// Do the route guage algorithm here.
        /// </summary>
        private void DoRouteGuage()
        {
            // Cannot do anything with out these two components.
            if (mRealStartTransform == null ||
                mRealGoalTransfrom == null ||
                mSpriteStartTransform == null ||
                mSpriteGoalTransform == null)
                return;

            for (int index = 0;
                index < mPlayersForm.Length;
                ++index)
            {
                // 拿到選手
                PlayerRegisterForm prf = mPlayersForm[index];
                if (prf.playerTransform == null || prf.spriteTransform == null)
                    continue;

                PutPlayerSpriteInPositionBaseOnRealDistance(prf);

                // make sure player are in range.
                PutPlayerSpriteInRange(prf);
            }

        }

        /// <summary>
        /// Measure the real world thing, then determine the positon
        /// of the sprite going to be located.
        /// </summary>
        /// <param name="prf">
        /// player to set.
        /// </param>
        private void PutPlayerSpriteInPositionBaseOnRealDistance(PlayerRegisterForm prf)
        {
            float statusBarCenter = mSpriteStartTransform.position.x + (mSpriteDistance / 2);

            Vector3 newSpritePos = prf.spriteTransform.position;
            newSpritePos.x = statusBarCenter + (prf.playerTransform.position.x * mDistanceRatio);
            prf.spriteTransform.position = newSpritePos;
        }

        /// <summary>
        /// Make sure all the player sprite inside the sprite range.
        /// </summary>
        /// <param name="prf"></param>
        private void PutPlayerSpriteInRange(PlayerRegisterForm prf)
        {
            Vector3 playerSpritePos = prf.spriteTransform.position;

            Vector3 spriteGoalPos = mSpriteGoalTransform.position;
            Vector3 spriteStartPos = mSpriteStartTransform.position;


            if (playerSpritePos.x > spriteGoalPos.x)
                playerSpritePos.x = spriteGoalPos.x;
            else if (playerSpritePos.x < spriteStartPos.x)
                playerSpritePos.x = spriteStartPos.x;

            prf.spriteTransform.position = playerSpritePos;
        }

    }
}
